# Generated by Django 3.2.12 on 2022-06-24 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_alter_review_content'),
        ('accounts', '0002_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='action',
        ),
        migrations.RemoveField(
            model_name='point',
            name='calculation',
        ),
        migrations.RemoveField(
            model_name='point',
            name='place',
        ),
        migrations.RemoveField(
            model_name='point',
            name='point',
        ),
        migrations.RemoveField(
            model_name='point',
            name='user',
        ),
        migrations.AlterField(
            model_name='point',
            name='point_now',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10)),
                ('calculation', models.BooleanField()),
                ('point', models.IntegerField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointLog', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
