# Generated by Django 3.2.12 on 2022-06-24 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220624_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='point_now',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='point', to=settings.AUTH_USER_MODEL),
        ),
    ]
