# Generated by Django 3.2.12 on 2022-06-22 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='review',
            field=models.ForeignKey(default='deleted_review', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='point', to='place.review'),
        ),
    ]
