# Generated by Django 3.2.12 on 2022-06-23 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_point_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point',
        ),
    ]
