# Generated by Django 3.2.12 on 2022-06-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_alter_reviewimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='place',
            new_name='placeId',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='reviewimage',
            old_name='review',
            new_name='reviewId',
        ),
    ]
