# Generated by Django 3.2.12 on 2022-06-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_auto_20220624_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='placeId',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reviewimage',
            old_name='reviewId',
            new_name='review',
        ),
    ]
